/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientWelcomeRouteImport } from './routes/patient/welcome'
import { Route as PatientDashboardIndexRouteImport } from './routes/patient/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientWelcomeRoute = PatientWelcomeRouteImport.update({
  id: '/patient/welcome',
  path: '/patient/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardIndexRoute = PatientDashboardIndexRouteImport.update({
  id: '/patient/dashboard/',
  path: '/patient/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patient/welcome': typeof PatientWelcomeRoute
  '/patient/dashboard/': typeof PatientDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patient/welcome': typeof PatientWelcomeRoute
  '/patient/dashboard': typeof PatientDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patient/welcome': typeof PatientWelcomeRoute
  '/patient/dashboard/': typeof PatientDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patient/welcome' | '/patient/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patient/welcome' | '/patient/dashboard'
  id: '__root__' | '/' | '/patient/welcome' | '/patient/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientWelcomeRoute: typeof PatientWelcomeRoute
  PatientDashboardIndexRoute: typeof PatientDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/welcome': {
      id: '/patient/welcome'
      path: '/patient/welcome'
      fullPath: '/patient/welcome'
      preLoaderRoute: typeof PatientWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard/': {
      id: '/patient/dashboard/'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard/'
      preLoaderRoute: typeof PatientDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientWelcomeRoute: PatientWelcomeRoute,
  PatientDashboardIndexRoute: PatientDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
