name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:24
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F backend... build
      - run: pnpm -F client-app... run build
